import React, { createContext, useContext, useState } from 'react';
import { SUPPORTED_LANGUAGES } from '../services/translationServiceFallback';

const LanguageContext = createContext(null);

export const UI_TRANSLATIONS = {
  en: {
    appName: 'Health Passport',
    tagline: 'Your Health. Your Records. Your Control.',
    dashboard: 'Dashboard',
    healthId: 'Digital Health ID',
    medicalRecords: 'Medical Records',
    aiSummary: 'AI Health Summary',
    reportExplainer: 'Report Explainer',
    translator: 'Multilingual Translator',
    appointments: 'Appointments',
    medicines: 'Medicines & Reminders',
    emergency: 'Emergency Profile',
    consentCenter: 'Consent Management',
    bills: 'Bills & Payments',
    documents: 'Documents',
    settings: 'Settings',
    patientPortal: 'Patient Portal',
    doctorPortal: 'Doctor Portal',
    logout: 'Logout',
    switchPersona: 'Switch Persona',
    requestAccess: 'Request Access',
    approve: 'Approve',
    deny: 'Deny',
    revoke: 'Revoke',
    aiDisclaimer: 'AI-GENERATED SUMMARY — VERIFY WITH ORIGINAL MEDICAL RECORDS',
    // New 8-section dashboard keys
    myHealth: 'My Health',
    medicalHistory: 'Medical History',
    ayurveda: 'Ayurveda',
    healthTimeline: 'Health Timeline',
    aiAssistant: 'AI Health Assistant',
    sharePassport: 'Share Health Passport',
    ayurvedaDisclaimer: 'Ayurvedic assessment — practitioner verification required',
    redFlag: 'Possible urgent symptom — contact hospital immediately',
    listen: 'Listen',
    speak: 'Speak',
    // Phase 3 — Clinical Intake
    startIntake: 'Start AI Clinical History',
    resumeIntake: 'Resume History',
    intakeProgress: 'History Progress',
    questionOf: 'Question {n} of {total}',
    confirmAnswer: 'Yes, that is correct',
    retryAnswer: 'Try again',
    confirmHistory: 'Confirm & Submit',
    editHistory: 'Edit Answers',
    historyConfirmed: 'History Confirmed',
    summaryTitle: 'AI Clinical Summary',
    summaryDisclaimer: 'AI-generated draft — clinician verification required',
    redFlagWarning: '⚠️ Your symptoms may require urgent medical attention. Please contact hospital or triage staff immediately.',
    intakeComplete: 'History complete! Generating summary...',
    verifiedByDoctor: 'Verified by',
    doctorNotes: 'Doctor Notes',
    chiefComplaint: 'Main Problem',
    hpi: 'History of Present Illness',
    pastMedical: 'Past Medical History',
    pastSurgical: 'Past Surgical History',
    medications: 'Current Medicines',
    allergies: 'Allergies',
    familyHistory: 'Family History',
    personalHistory: 'Personal History',
    reviewOfSystems: 'Review of Systems',
    // Phase 4 — Ayurveda
    ayurvedaProfile: 'Ayurveda Profile',
    prakriti: 'Prakriti',
    vikriti: 'Vikriti',
    agni: 'Agni (Digestive Fire)',
    koshtha: 'Koshtha (Bowel Habit)',
    ahara: 'Ahara (Diet)',
    vihara: 'Vihara (Lifestyle)',
    nidana: 'Nidana (Cause)',
    dashavidha: 'Dashavidha Pariksha',
    ayurvedicMedicines: 'Ayurvedic Medicines',
    treatmentHistory: 'Treatment History',
    treatmentResponse: 'Treatment Response',
    patientReported: 'Patient Reported',
    practitionerAssessed: 'Practitioner Assessed',
    vaidyaVerified: 'Vaidya Verified',
    addMedicine: 'Add Medicine',
    addTreatment: 'Add Treatment',
    addResponse: 'Add Response',
    ayurvedaDisclaimer2: 'AI-assisted history — practitioner verification required. AI does not diagnose Prakriti or prescribe Ayurvedic medicines.',
    beforeTreatment: 'Before Treatment',
    afterTreatment: 'After Treatment',
    symptomScore: 'Symptom Severity',
    sleepQuality: 'Sleep Quality',
    energyLevel: 'Energy Level',
    digestion: 'Digestion',
    // Phase 5 — OCR Document Digitisation
    scanDocument: 'Scan Document',
    uploadDocument: 'Upload Document',
    digitizeDocument: 'Digitize Document',
    originalDocument: 'Original Document',
    extractedText: 'Extracted Text',
    abnormalRange: 'Value appears outside the reference range shown on the report. Please discuss with your clinician.',
    aiDisclaimerOcr: 'AI-assisted parsing — clinician verification required.',
    confirmDigitization: 'Confirm Digitization',
    needsVerification: 'Needs Verification',
    verified: 'Verified',
    processing: 'Processing...'
  },
  hi: {
    appName: 'हेल्थ पासपोर्ट',
    tagline: 'आपका स्वास्थ्य। आपके रिकॉर्ड्स। आपका नियंत्रण।',
    dashboard: 'डैशबोर्ड',
    healthId: 'डिजिटल हेल्थ आईडी',
    medicalRecords: 'चिकित्सा रिकॉर्ड्स',
    aiSummary: 'एआई स्वास्थ्य सारांश',
    reportExplainer: 'रिपोर्ट व्याख्याता',
    translator: 'बहुभाषी अनुवादक',
    appointments: 'अपॉइंटमेंट्स',
    medicines: 'दवाइयां और रिमाइंडर',
    emergency: 'आपातकालीन प्रोफ़ाइल',
    consentCenter: 'सहमति केंद्र',
    bills: 'बिल और भुगतान',
    documents: 'दस्तावेज',
    settings: 'सेटिंग्स',
    patientPortal: 'मरीज पोर्टल',
    doctorPortal: 'डॉक्टर पोर्टल',
    logout: 'लॉग आउट',
    switchPersona: 'प्रोफ़ाइल बदलें',
    requestAccess: 'अनुमति का अनुरोध करें',
    approve: 'स्वीकार करें',
    deny: 'अस्वीकार करें',
    revoke: 'वापस लें',
    aiDisclaimer: 'एआई जनरेटेड सारांश — मूल चिकित्सा रिकॉर्ड से सत्यापित करें',
    myHealth: 'मेरा स्वास्थ्य',
    medicalHistory: 'चिकित्सा इतिहास',
    ayurveda: 'आयुर्वेद',
    healthTimeline: 'स्वास्थ्य समयरेखा',
    aiAssistant: 'एआई स्वास्थ्य सहायक',
    sharePassport: 'हेल्थ पासपोर्ट साझा करें',
    ayurvedaDisclaimer: 'आयुर्वेदिक मूल्यांकन — चिकित्सक सत्यापन आवश्यक',
    redFlag: 'संभावित आपातकालीन लक्षण — तुरंत अस्पताल से संपर्क करें',
    listen: 'सुनें',
    speak: 'बोलें',
    // Phase 3 — Clinical Intake
    startIntake: 'एआई क्लिनिकल इतिहास शुरू करें',
    resumeIntake: 'इतिहास जारी रखें',
    intakeProgress: 'इतिहास प्रगति',
    questionOf: 'प्रश्न {n} / {total}',
    confirmAnswer: 'हां, यह सही है',
    retryAnswer: 'फिर से प्रयास करें',
    confirmHistory: 'पुष्टि करें और सबमिट करें',
    editHistory: 'उत्तर संपादित करें',
    historyConfirmed: 'इतिहास पुष्टि हो गया',
    summaryTitle: 'एआई क्लिनिकल सारांश',
    summaryDisclaimer: 'एआई जनरेटेड ड्राफ्ट — चिकित्सक सत्यापन आवश्यक',
    redFlagWarning: '⚠️ आपके लक्षणों के लिए तत्काल चिकित्सा देखभाल की आवश्यकता हो सकती है।',
    intakeComplete: 'इतिहास पूर्ण! सारांश तैयार हो रहा है...',
    chiefComplaint: 'मुख्य समस्या',
    hpi: 'वर्तमान बीमारी का इतिहास',
    pastMedical: 'पिछली चिकित्सा इतिहास',
    pastSurgical: 'पिछली शल्य चिकित्सा इतिहास',
    medications: 'वर्तमान दवाइयां',
    allergies: 'एलर्जी',
    familyHistory: 'पारिवारिक इतिहास',
    personalHistory: 'व्यक्तिगत इतिहास',
    reviewOfSystems: 'प्रणालियों की समीक्षा',
    verifiedByDoctor: 'सत्यापित:',
    doctorNotes: 'डॉक्टर नोट्स',
    // Phase 4 — Ayurveda
    ayurvedaProfile: 'आयुर्वेद प्रोफाइल',
    prakriti: 'प्रकृति',
    vikriti: 'विकृति',
    agni: 'अग्नि (पाचन शक्ति)',
    koshtha: 'कोष्ठ (मल स्वभाव)',
    ahara: 'आहार (खान-पान)',
    vihara: 'विहार (जीवनशैली)',
    nidana: 'निदान (कारण)',
    dashavidha: 'दशविध परीक्षा',
    ayurvedicMedicines: 'आयुर्वेदिक दवाइयां',
    treatmentHistory: 'उपचार इतिहास',
    treatmentResponse: 'उपचार प्रतिक्रिया',
    patientReported: 'मरीज द्वारा बताया',
    practitionerAssessed: 'वैद्य द्वारा मूल्यांकित',
    vaidyaVerified: 'वैद्य सत्यापित',
    addMedicine: 'दवा जोड़ें',
    addTreatment: 'उपचार जोड़ें',
    addResponse: 'प्रतिक्रिया जोड़ें',
    ayurvedaDisclaimer2: 'एआई सहायता प्राप्त इतिहास — वैद्य सत्यापन आवश्यक।',
    beforeTreatment: 'उपचार से पहले',
    afterTreatment: 'उपचार के बाद',
    symptomScore: 'लक्षण ग्रेड',
    sleepQuality: 'नींद की गुणवत्ता',
    energyLevel: 'उर्जा स्तर',
    digestion: 'पाचन',
    // Phase 5 — OCR Document Digitisation
    scanDocument: 'दस्तावेज़ स्कैन करें',
    uploadDocument: 'दस्तावेज़ अपलोड करें',
    digitizeDocument: 'दस्तावेज़ डिजिटाइज़ करें',
    originalDocument: 'मूल दस्तावेज़',
    extractedText: 'निकाला गया टेक्स्ट',
    abnormalRange: 'मूल्य रिपोर्ट पर दिखाए गए संदर्भ सीमा से बाहर दिखाई देता है। कृपया अपने चिकित्सक से चर्चा करें।',
    aiDisclaimerOcr: 'एआई-सहायता प्राप्त पार्सिंग — चिकित्सक सत्यापन आवश्यक।',
    confirmDigitization: 'डिजिटलीकरण की पुष्टि करें',
    needsVerification: 'सत्यापन की आवश्यकता है',
    verified: 'सत्यापित',
    processing: 'प्रसंस्करण हो रहा है...'
  },
  mr: {
    appName: 'हेल्थ पासपोर्ट',
    tagline: 'तुमचे आरोग्य. तुमच्या नोंदी. तुमचे नियंत्रण.',
    dashboard: 'डॅशबोर्ड',
    healthId: 'डिजिटल हेल्थ आयडी',
    medicalRecords: 'वैद्यकीय नोंदी',
    aiSummary: 'एआय आरोग्य सारांश',
    reportExplainer: 'रिपोर्ट समजावणारा',
    translator: 'भाषांतरकार',
    appointments: 'अपॉइंटमेंट्स',
    medicines: 'औषधे आणि स्मरणपत्रे',
    emergency: 'आपत्कालीन प्रोफाईल',
    consentCenter: 'संमती व्यवस्थापन',
    bills: 'बिले आणि पेमेंट',
    documents: 'कागदपत्रे',
    settings: 'सेटिंग्ज',
    patientPortal: 'रुग्ण पोर्टल',
    doctorPortal: 'डॉक्टर पोर्टल',
    logout: 'लॉग आऊट',
    switchPersona: 'प्रोफाइल बदला',
    requestAccess: 'प्रवेश विनंती करा',
    approve: 'मंजूर करा',
    myHealth: 'माझे आरोग्य',
    medicalHistory: 'वैद्यकीय इतिहास',
    ayurveda: 'आयुर्वेद',
    healthTimeline: 'आरोग्य कालरेषा',
    aiAssistant: 'एआय आरोग्य सहाय्यक',
    sharePassport: 'हेल्थ पासपोर्ट शेअर करा',
    ayurvedaDisclaimer: 'आयुर्वेदिक मूल्यांकन — वैद्य सत्यापन आवश्यक',
    redFlag: 'तातडीचे लक्षण असू शकते — त्वरित रुग्णालयाशी संपर्क करा',
    deny: 'नाकारा',
    revoke: 'रद्द करा',
    aiDisclaimer: 'एआय जनरेट केलेला सारांश — मूळ वैद्यकीय नोंदींसह सत्यापित करा',
    listen: 'ऐका',
    speak: 'बोला',
    // Phase 3 — Clinical Intake
    startIntake: 'एआय क्लिनिकल इतिहास सुरू करा',
    resumeIntake: 'इतिहास पुढे सुरू करा',
    intakeProgress: 'इतिहास प्रगती',
    questionOf: 'प्रश्न {n} / {total}',
    confirmAnswer: 'हो, हे बरोबर आहे',
    retryAnswer: 'पुन्हा प्रयत्न करा',
    confirmHistory: 'पुष्टी करा आणि सबमिट करा',
    editHistory: 'उत्तरे संपादित करा',
    historyConfirmed: 'इतिहास पुष्टी झाला',
    summaryTitle: 'एआय क्लिनिकल सारांश',
    summaryDisclaimer: 'एआय-निर्मित मसुदा — वैद्य सत्यापन आवश्यक',
    redFlagWarning: '⚠️ तुमच्या लक्षणांसाठी तातडीची वैद्यकीय मदत आवश्यक असू शकते।',
    intakeComplete: 'इतिहास पूर्ण! सारांश तयार होत आहे...',
    chiefComplaint: 'मुख्य तक्रार',
    hpi: 'सध्याच्या आजाराचा इतिहास',
    pastMedical: 'मागील वैद्यकीय इतिहास',
    pastSurgical: 'मागील शस्त्रक्रिया इतिहास',
    medications: 'सध्याची औषधे',
    allergies: 'ऍलर्जी',
    familyHistory: 'कौटुंबिक इतिहास',
    personalHistory: 'वैयक्तिक इतिहास',
    reviewOfSystems: 'प्रणालींचा आढावा',
    verifiedByDoctor: 'सत्यापित:',
    doctorNotes: 'डॉक्टर नोट्स',
    // Phase 4 — Ayurveda
    ayurvedaProfile: 'आयुर्वेद प्रोफाइल',
    prakriti: 'प्रकृती',
    vikriti: 'विकृती',
    agni: 'अग्नी (पचनशक्ती)',
    koshtha: 'कोष्ठ (मल स्वभाव)',
    ahara: 'आहार (अन्न)',
    vihara: 'विहार (जीवनशैली)',
    nidana: 'निदान (कारण)',
    dashavidha: 'दशविध परीक्षा',
    ayurvedicMedicines: 'आयुर्वेदिक औषधे',
    treatmentHistory: 'उपचार इतिहास',
    treatmentResponse: 'उपचार प्रतिसाद',
    patientReported: 'रुग्णाने नोंदवलेले',
    practitionerAssessed: 'वैद्याने मूल्यमापन केलेले',
    vaidyaVerified: 'वैद्य-सत्यापित',
    addMedicine: 'औषध जोडा',
    addTreatment: 'उपचार जोडा',
    addResponse: 'प्रतिसाद जोडा',
    ayurvedaDisclaimer2: 'एआय-सहाय इतिहास — वैद्य सत्यापन आवश्यक।',
    beforeTreatment: 'उपचारापूर्वी',
    afterTreatment: 'उपचारानंतर',
    symptomScore: 'लक्षण तीव्रता',
    sleepQuality: 'झोपेची गुणवत्ता',
    energyLevel: 'उर्जा पातळी',
    digestion: 'पचन',
    // Phase 5 — OCR Document Digitisation
    scanDocument: 'दस्तऐवज स्कॅन करा',
    uploadDocument: 'दस्तऐवज अपलोड करा',
    digitizeDocument: 'दस्तऐवज डिजिटायझ करा',
    originalDocument: 'मूळ दस्तऐवज',
    extractedText: 'काढलेला मजकूर',
    abnormalRange: 'मूल्य अहवालात दर्शविलेल्या संदर्भ श्रेणीबाहेर दिसत आहे. कृपया आपल्या डॉक्टरांशी चर्चा करा.',
    aiDisclaimerOcr: 'एआय-सहाय्यक पार्सिंग — चिकित्सक सत्यापन आवश्यक.',
    confirmDigitization: 'डिजिटायझेशनची पुष्टी करा',
    needsVerification: 'पडताळणी आवश्यक आहे',
    verified: 'सत्यापित',
    processing: 'प्रक्रिया चालू आहे...'
  },
  gu: {
    appName: 'હેલ્થ પાસપોર્ટ',
    tagline: 'તમારું સ્વાસ્થ્ય. તમારા રેકોર્ડ્સ. તમારું નિયંત્રણ.',
    dashboard: 'ડેશબોર્ડ',
    healthId: 'ડિજિટલ હેલ્થ આઈડી',
    medicalRecords: 'તબીબી રેકોર્ડ્સ',
    aiSummary: 'એઆઈ આરોગ્ય સારાંશ',
    reportExplainer: 'રિપોર્ટ એક્સપ્લેનર',
    translator: 'બહુભાષી અનુવાદક',
    appointments: 'મુલાકાતો',
    medicines: 'દવાઓ અને રીમાઇન્ડર્સ',
    emergency: 'ઇમરજન્સી પ્રોફાઇલ',
    consentCenter: 'સંમતિ વ્યવસ્થાપન',
    bills: 'બિલ અને ચુકવણી',
    documents: 'દસ્તાવેજો',
    settings: 'સેટિંગ્સ',
    patientPortal: 'દર્દી પોર્ટલ',
    doctorPortal: 'ડૉક્ટર પોર્ટલ',
    logout: 'લૉગ આઉટ',
    switchPersona: 'પ્રોફાઇલ બદલો',
    requestAccess: 'પ્રવેશની વિનંતી કરો',
    approve: 'મંજૂર કરો',
    deny: 'અસ્વીકાર કરો',
    revoke: 'રદ કરો',
    aiDisclaimer: 'એઆઈ જનરેટેડ સારાંશ — મૂળ મેડિકલ રેકોર્ડ સાથે ચકાસો'
  },
  ta: {
    appName: 'ஹெல்த் பாஸ்போர்ட்',
    tagline: 'உங்கள் உடல்நலம். உங்கள் பதிவுகள். உங்கள் கட்டுப்பாடு.',
    dashboard: 'டாஷ்போர்டு',
    healthId: 'டிஜிட்டல் ஹெல்த் ஐடி',
    medicalRecords: 'மருத்துவப் பதிவுகள்',
    aiSummary: 'AI சுகாதார சுருக்கம்',
    reportExplainer: 'அறிக்கை விளக்கவுரை',
    translator: 'மொழிபெயர்ப்பாளர்',
    appointments: 'முன்பதிவுகள்',
    medicines: 'மருந்துகள் & நினைவூட்டல்கள்',
    emergency: 'அவசர சிகிச்சை சுயவிவரம்',
    consentCenter: 'ஒப்புதல் மையம்',
    bills: 'பில்கள் & பணம் செலுத்துதல்',
    documents: 'ஆவணங்கள்',
    settings: 'அமைப்புகள்',
    patientPortal: 'நோயாளி போர்டல்',
    doctorPortal: 'மருத்துவர் போர்டல்',
    logout: 'வெளியேறு',
    switchPersona: 'நபரை மாற்றவும்',
    requestAccess: 'அனுமதி கோருங்கள்',
    approve: 'ஏற்கவும்',
    deny: 'நிராகரிக்கவும்',
    revoke: 'ரத்து செய்யவும்',
    aiDisclaimer: 'AI உருவாக்கிய சுருக்கம் — அசல் மருத்துவப் பதிவுகளுடன் சரிபார்க்கவும்'
  },
  te: {
    appName: 'హెల్త్ పాస్‌పోర్ట్',
    tagline: 'మీ ఆరోగ్యం. మీ రికార్డులు. మీ నియంత్రణ.',
    dashboard: 'డాష్‌బోర్డ్',
    healthId: 'డిజిటల్ హెల్త్ ఐడీ',
    medicalRecords: 'వైద్య రికార్డులు',
    aiSummary: 'AI ఆరోగ్య సారాంశం',
    reportExplainer: 'రిపోర్ట్ వివరణ',
    translator: 'బహుభాషా అనువాదకుడు',
    appointments: 'అపాయింట్‌మెంట్‌లు',
    medicines: 'మందులు & రిమైండర్‌లు',
    emergency: 'అత్యవసర ప్రొఫైల్',
    consentCenter: 'సమ్మతి నిర్వహణ',
    bills: 'బిల్లులు & చెల్లింపులు',
    documents: 'పత్రాలు',
    settings: 'సెట్టింగ్‌లు',
    patientPortal: 'రోగి పోర్టల్',
    doctorPortal: 'వైద్యుల పోర్టల్',
    logout: 'లాగ్ అవుట్',
    switchPersona: 'ప్రొఫైల్ మార్చండి',
    requestAccess: 'యాక్సెస్ అభ్యర్థించండి',
    approve: 'ఆమోదించండి',
    deny: 'తిరస్కరించండి',
    revoke: 'రద్దు చేయండి',
    aiDisclaimer: 'AI రూపొందించిన సారాంశం — అసలు వైద్య రికార్డులతో ధృవీకరించండి'
  },
  bn: {
    appName: 'হেলথ পাসপোর্ট',
    tagline: 'আপনার স্বাস্থ্য। আপনার রেকর্ড। আপনার নিয়ন্ত্রণ।',
    dashboard: 'ড্যাশবোর্ড',
    healthId: 'ডিজিটাল হেলথ আইডি',
    medicalRecords: 'মেডিকেল রেকর্ড',
    aiSummary: 'এআই স্বাস্থ্য সারাংশ',
    reportExplainer: 'রিপোর্ট ব্যাখ্যাকারী',
    translator: 'বহুভাষিক অনুবাদক',
    appointments: 'অ্যাপয়েন্টমেন্ট',
    medicines: 'ওষুধ এবং অনুস্মারক',
    emergency: 'জরুরী প্রোফাইল',
    consentCenter: 'সম্মতি কেন্দ্র',
    bills: 'বিল ও পেমেন্ট',
    documents: 'নথিপত্র',
    settings: 'সেটিংস',
    patientPortal: 'রোগী পোর্টাল',
    doctorPortal: 'ডাক্তার পোর্টাল',
    logout: 'লগ আউট',
    switchPersona: 'প্রোফাইল পরিবর্তন করুন',
    requestAccess: 'অনুমতির অনুরোধ করুন',
    approve: 'অনুমোদন করুন',
    deny: 'প্রত্যাখ্যান করুন',
    revoke: 'বাতিল করুন',
    aiDisclaimer: 'এআই প্রস্তুত সারাংশ — মূল মেডিকেল রেকর্ডের সাথে যাচাই করুন'
  }
};

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' }
];

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  const t = (key) => {
    const langSet = UI_TRANSLATIONS[currentLanguage] || UI_TRANSLATIONS.en;
    return langSet[key] || UI_TRANSLATIONS.en[key] || key;
  };

  const changeLanguage = (langCode) => {
    if (UI_TRANSLATIONS[langCode]) {
      setCurrentLanguage(langCode);
      localStorage.setItem('hp_lang', langCode);
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        changeLanguage,
        t,
        languages: LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
